# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [ "nvidia" ];
    kernelModules = [ "i2c-dev" "i2c-piix4" ];
    extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];
    supportedFilesystems = [ "ntfs" ];
    kernelParams = [
      "acpi_enforce_resources=lax"
      "pci=assign-busses"
      "microcode.amd_sha_check=off"
      "zswap.enabled=1"
      "zswap.max_pool_percent=50"
      "zswap.shrinker_enabled=1"
      "zswap.compressor=zstd"
      "zswap.accept_threshold_percent=90"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a0985add-f02e-40c4-8823-000e95210414";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0459-BB7B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/disk/by-uuid/b7443e0f-4a6a-4ef5-8e6a-86adc02fa1c4";
      fsType = "btrfs";
      options = [ "users" "nofail" "exec" "noatime"];
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/CC6EF8376EF81BC0";
      fsType = "ntfs-3g";
      options = [ "users" "nofail" "exec" "noatime"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dce48e6e-342d-4ea5-937a-7c2d3b004798"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.firmware = with pkgs; [ pkgs.linux-firmware ];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.i2c.enable = true;
}
