cursor #e1e2ea
cursor_text_color #c2c6d4

foreground            #e1e2ea
background            #111319
selection_foreground  #1e3051
selection_background  #b5c7ef
url_color             #acc7ff

color0   #111319
color1   #e64c46
color2   #6fd66e
color3   #dbd27b
color4   #5e80ce
color5   #8d9dbf
color6   #acc7ff
color7   #abb2bf
color8   #5c6370
color9   #e0605f
color10  #87e086
color11  #e8e097
color12  #b8d5ff
color13  #507cac
color14  #6976b1
color15  #ffffff
