# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #7795CD

background #0E1015
foreground #D8ECF0

color0 #37383D
color1 #0B2443
color2 #102E80
color3 #184E90
color4 #2374B9
color5 #657688
color6 #6C979E
color7 #BFDCE1
color8 #869A9D
color9 #0E3059
color10 #153EAA
color11 #2068C0
color12 #2F9BF6
color13 #879DB5
color14 #90C9D3
color15 #BFDCE1

mark1_foreground #56949E
mark2_foreground #99D6E1
mark3_foreground #56949E
